In [9]:
def try_except(x,y):
    try:
        a=x/y
        print('The division result will be ',a)
    except Exception as e:
        print(e)


In [10]:
try_except(5,0)

division by zero


In [19]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
output=[(a+' '+b+' '+c) for a in subjects for b in verbs for c in objects]
for i in output:
    print(i)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [2]:
import numpy as np

def generateMatrix(element,column):
    return np.column_stack([element**(column-1-i) for i in range(column)])

print(generateMatrix(np.array([1, 2, 3, 4,5]),4))

#Using Vendor method
def generateMatrix(element,column):
    return np.vander(element,column)

print("\n Using Vendor Method : \n")
print(generateMatrix(np.array([1, 2, 3, 4,5]),4))

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]

 Using Vendor Method : 

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
